function(create_resource_bundle name)
    set(include_directory "${CMAKE_CURRENT_BINARY_DIR}/resources/${name}")
    set(file "${include_directory}/${name}.hpp")

    set(include_guard "${name}_HPP_")
    string(TOUPPER "${include_guard}" include_guard)

    file(MAKE_DIRECTORY "${include_directory}")
    file(WRITE  "${file}" "// This file is generated by CMake. Do not edit.\n")
    file(APPEND "${file}" "#ifndef ${include_guard}\n")
    file(APPEND "${file}" "#define ${include_guard}\n")
    file(APPEND "${file}" "#pragma once\n\n")

    string(RANDOM LENGTH 13 string_guard)

    foreach(arg IN LISTS ARGN)
        if (NOT DEFINED resource_name)
            set(resource_name ${arg})
            continue()
        endif()

        file(READ ${arg} content)

        file(APPEND "${file}" "inline constexpr const char *${resource_name} = R\"STR${string_guard}(\n")
        file(APPEND "${file}" "${content}")
        file(APPEND "${file}" ")STR${string_guard}\";\n\n")

        unset(resource_name)
    endforeach()

    file(APPEND "${file}" "#endif // ${include_guard}\n")

    add_library(${name} INTERFACE)
    target_include_directories(${name} INTERFACE "${include_directory}")
endfunction()
